class GamesPlay {
  static List myGames = [
    {
      'image': 'assets/games/8ball.jpg',
      'name': '8 Ball Pool',
      'rating': '4.3',
      'company': 'Miniclip.com',
      'reviews': '50K',
      'download': '100M',
      'quote': 'The most download pool game.',
    },
    {
      'image': 'assets/games/carrom.jpg',
      'name': 'Carrom Pool',
      'rating': '4.2',
      'company': 'Miniclip.com',
      'reviews': '50K',
      'download': '10M',
      'quote': 'Relive your childhood memories.',
    },
    {
      'image': 'assets/games/coin.jpg',
      'name': 'Coin Master',
      'rating': '4.2',
      'company': 'Moon Active',
      'reviews': '50K',
      'download': '100M',
      'quote': 'Play the Best Adventure Game.',
    },
    {
      'image': 'assets/games/ludo.jpg',
      'name': 'Ludo',
      'rating': '100K',
      'company': 'Yarsa Games',
      'reviews': '40K',
      'download': '50M',
      'quote': 'Ludo game is fun to play with family.',
    },
    {
      'image': 'assets/games/spider.jpg',
      'name': 'Spider Solitaire',
      'rating': '4.2',
      'company': 'nerByte GmbH',
      'reviews': '3.9',
      'download': '100M',
      'quote': 'Card Game most Played Game.',
    },
    {
      'image': 'assets/games/traffic.jpg',
      'name': 'Traffic Ryder',
      'rating': '4.6',
      'company': 'Highway Games',
      'reviews': '450K',
      'download': '12M',
      'quote': 'Play Bike Games and Enjoy.',
    },
  ];

  static List myNewGames = [
    {
      'image': 'assets/games/asphalt.jpg',
      'name': 'Asphalt 9',
      'rating': '4.3',
      'company': 'Gameloft SE',
      'reviews': '100K',
      'download': '100M',
      'quote': 'The Sport Racing game.',
    },
    {
      'image': 'assets/games/boxing.jpg',
      'name': 'Boxing Star',
      'rating': '4.2',
      'company': 'Sports',
      'reviews': '50K',
      'download': '10M',
      'quote': 'Relive your Boxing memories.',
    },
    {
      'image': 'assets/games/city.jpg',
      'name': 'City Island',
      'rating': '4.2',
      'company': 'Simulation',
      'reviews': '50K',
      'download': '100M',
      'quote': 'Play the Best City Island Game.',
    },
    {
      'image': 'assets/games/phase 10.png',
      'name': 'Phase 10',
      'rating': '100K',
      'company': 'Last Games',
      'reviews': '50K',
      'download': '50M',
      'quote': 'World tour with phase 10.',
    },
    {
      'image': 'assets/games/sort.jpg',
      'name': 'Sort Master',
      'rating': '4.2',
      'company': 'Puzzle',
      'reviews': '100K',
      'download': '100M',
      'quote': 'Sort Master Mind Game.',
    },
    {
      'image': 'assets/games/zoombie.jpg',
      'name': 'Zombie Hunter',
      'rating': '4.6',
      'company': 'Arcade',
      'reviews': '40K',
      'download': '12M',
      'quote': 'Play Hunter Game with Zombies.',
    },
  ];
  static List mySuggestedGames = [
    {
      'image': 'assets/games/art.jpg',
      'name': 'Art Games',
      'rating': '4.3',
      'company': 'Kala Gamers',
      'reviews': '30K',
      'download': '100M',
      'quote': 'The Art Making game.',
    },
    {
      'image': 'assets/games/coc.jpg',
      'name': 'Clash of Clans',
      'rating': '4.2',
      'company': 'COC Developers',
      'reviews': '50K',
      'download': '10M',
      'quote': 'Create Your Own Empire.',
    },
    {
      'image': 'assets/games/cooking.jpg',
      'name': 'Cooking Game',
      'rating': '4.2',
      'company': 'Angel Gamers',
      'reviews': '50K',
      'download': '100M',
      'quote': 'Play the Best Cooking Game.',
    },
    {
      'image': 'assets/games/cricket.jpg',
      'name': 'Cricket League',
      'rating': '100K',
      'company': 'Gully Gamers',
      'reviews': '100K',
      'download': '50M',
      'quote': 'Play Cricket with your Friends.',
    },
    {
      'image': 'assets/games/race.jpg',
      'name': 'Racing Game',
      'rating': '4.2',
      'company': 'Racers The Rider',
      'reviews': '300K',
      'download': '100M',
      'quote': 'Virtually racing with your friends.',
    },
    {
      'image': 'assets/games/wcc3.jpg',
      'name': 'World Cricket',
      'rating': '4.6',
      'company': 'WCC',
      'reviews': '40K',
      'download': '12M',
      'quote': 'Play Best Cricket Game in The world.',
    },
  ];
}
