class Globals {
  static bool isAndroid = true;

  static List myApps = [
    {
      'image': 'assets/images/alexa.png',
      'name': 'Alexa',
      'rating': '4.2',
      'company': 'Amazon',
      'reviews': '95K',
      'download': '5M',
      'quote': "Smart Device.",
    },
    {
      'image': 'assets/images/firefox.jpg',
      'name': 'FireFox',
      'rating': '4.4',
      'company': 'Mozila',
      'reviews': '430K',
      'download': '100M',
      'quote': "Protect your online privacy.",
    },
    {
      'image': 'assets/images/amazon.png',
      'name': 'Amazon Seller',
      'rating': '4.1',
      'company': 'Amazon Mobile LLC',
      'reviews': '100K',
      'download': '10M',
      'quote': "Start your online business.",
    },
    {
      'image': 'assets/images/instagram.jpg',
      'name': 'Instagram',
      'rating': '4.3',
      'company': 'Instagram',
      'reviews': '100M',
      'download': '200M',
      'quote': "Share videos,photos,and fun,",
    },
    {
      'image': 'assets/images/snapchat.png',
      'name': 'Snapchat',
      'rating': '4.1',
      'company': 'Snap Inc',
      'reviews': '250K',
      'download': '2M',
      'quote': "Share the snap",
    },
    {
      'image': 'assets/images/whatsapp.png',
      'name': 'Whatsapp',
      'rating': '4.6',
      'company': 'Whatsapp LLC',
      'reviews': '950K',
      'download': '50M',
      'quote': "Simple. Reliable. Private.",
    },
  ];
  static List myNewApp = [
    {
      'image': 'assets/images/aha.png',
      'name': 'Aha OTT',
      'rating': '4.2',
      'company': 'Arha Media',
      'reviews': '800K',
      'download': '50M',
      'quote': "Watch Movies & Web Series.",
    },
    {
      'image': 'assets/images/gallary.jpg',
      'name': 'Gallery',
      'rating': '4.2',
      'company': 'Gallery Studio LLC',
      'reviews': '19K',
      'download': '200K',
      'quote': "Smart Gallery is an Excellent Photos.",
    },
    {
      'image': 'assets/images/home.jpg',
      'name': 'Google Home',
      'rating': '4.5',
      'company': 'Google LLC',
      'reviews': '950K',
      'download': '50M',
      'quote': "Set Up and Control your Gadgets.",
    },
    {
      'image': 'assets/images/invoice.jpg',
      'name': 'Invoice App',
      'rating': '4.2',
      'company': 'Invoice Simple',
      'reviews': '941K',
      'download': '20M',
      'quote': "Create an invoice for free",
    },
    {
      'image': 'assets/images/khatabook.png',
      'name': 'Khatabook',
      'rating': '4.3',
      'company': 'Khatabook Business app',
      'reviews': '150K',
      'download': '10M',
      'quote': "Khatabook business manager.",
    },
  ];
  static List myNewAppSuggested = [
    {
      'image': 'assets/images/cred.png',
      'name': 'CRED',
      'rating': '4.2',
      'company': 'Dreamplug Technologies',
      'reviews': '95K',
      'download': '5M',
      'quote': "discover the endless cashback's",
    },
    {
      'image': 'assets/images/discovery.jpg',
      'name': 'Discovery',
      'rating': '4.2',
      'company': 'Discovery LLC',
      'reviews': '95K',
      'download': '5M',
      'quote': "discover the al new movies.",
    },
    {
      'image': 'assets/images/lenskart.png',
      'name': 'Lenskart',
      'rating': '4.5',
      'company': 'Lenskart Eyewear',
      'reviews': '125K',
      'download': '500K',
      'quote': "Eye-glasses App",
    },
    {
      'image': 'assets/images/linkdin.png',
      'name': 'LinkdIn',
      'rating': '4.2',
      'company': 'LinkdIn',
      'reviews': '950K',
      'download': '20M',
      'quote': "Discover new job opportunities.",
    },
    {
      'image': 'assets/images/shemaroo.png',
      'name': 'Shemaroo Me',
      'rating': '4.3',
      'company': 'Shemaroo Entertainment',
      'reviews': '95K',
      'download': '5M',
      'quote': "Entertainment Entertainment & Entertainment.",
    },
  ];
}
